services:
  task-service:
    build:
      context: .
      dockerfile: ./src/microservices/tasks/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - PORT=8080
    command: ["python", "task_service.py"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  create-project:
    build:
      context: .
      dockerfile: ./src/microservices/projects/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    command: ["python","createProject.py"]

  get-project:
    build:
      context: .
      dockerfile: ./src/microservices/projects/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    command: ["python","getProject.py"]

  user-service:
    build:
      context: .
      dockerfile: ./src/microservices/users/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - VITE_TASK_OWNER_ID=${VITE_TASK_OWNER_ID}
      - PORT=8081
    command: ["python", "user_service.py"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build:
      context: .
      dockerfile: ./src/microservices/users/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - PORT=8086
    command: ["python", "userAuthentication.py"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3