<template>
  <a-modal
    v-model:open="modalVisible"
    :title="null"
    :footer="null"
    :width="1200"
    :closable="false"
    :maskClosable="false"
    @cancel="handleClose"
    class="report-preview-modal"
  >
    <!-- Header -->
    <div class="modal-header">
      <div class="header-content">
        <div class="icon-wrapper">
          <FileTextOutlined class="header-icon" />
        </div>
        <div class="header-text">
          <h3 class="modal-title">{{ getReportTitle() }} Preview</h3>
          <p class="modal-subtitle">Review the report before exporting to PDF</p>
        </div>
      </div>
      <a-button
        type="text"
        @click="handleClose"
        class="close-button"
        :icon="h(CloseOutlined)"
      />
    </div>

    <!-- Report Content -->
    <div class="report-content" v-if="reportData">
      <!-- Report Overview -->
      <div class="report-section">
        <h2 class="section-title">Report Overview</h2>
        <div class="overview-grid">
          <div class="overview-item">
            <span class="label">Report Type:</span>
            <span class="value">{{ getReportTitle() }}</span>
          </div>
          <div class="overview-item">
            <span class="label">Generated By:</span>
            <span class="value">{{ reportData.generated_by }}</span>
          </div>
          <div class="overview-item">
            <span class="label">User Role:</span>
            <span class="value">{{ reportData.user_role }}</span>
          </div>
          <div class="overview-item">
            <span class="label">Generated At:</span>
            <span class="value">{{ formatDate(reportData.generated_at) }}</span>
          </div>
          <div v-if="getTargetInfo()" class="overview-item">
            <span class="label">{{ getTargetLabel() }}:</span>
            <span class="value">{{ getTargetInfo() }}</span>
          </div>
          <div v-if="getFiltersInfo()" class="overview-item full-width">
            <span class="label">Applied Filters:</span>
            <span class="value">{{ getFiltersInfo() }}</span>
          </div>
        </div>
      </div>

      <!-- Performance Summary -->
      <div class="report-section">
        <h2 class="section-title">Performance Summary</h2>
        <div class="summary-container">
          <!-- Pie Chart -->
          <div class="pie-chart-container" v-if="reportData.charts?.length > 0">
            <canvas ref="pieChartCanvas" width="400" height="450"></canvas>
          </div>

          <!-- Stats Cards -->
          <div class="stats-cards">
            <div class="stat-item">
              <span class="stat-label">Total Tasks</span>
              <span class="stat-value">{{ reportData.summary?.total_tasks || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.completed_tasks !== undefined" class="stat-item">
              <span class="stat-label">Completed</span>
              <span class="stat-value completed-color">{{ reportData.summary.completed_tasks || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.total_completed !== undefined" class="stat-item">
              <span class="stat-label">Total Completed</span>
              <span class="stat-value completed-color">{{ reportData.summary.total_completed || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.total_members" class="stat-item">
              <span class="stat-label">Team Members</span>
              <span class="stat-value">{{ reportData.summary.total_members }}</span>
            </div>
            <div v-if="reportData.summary?.avg_completion_rate !== undefined" class="stat-item highlight">
              <span class="stat-label">Avg Completion Rate</span>
              <span class="stat-value">{{ Math.round(reportData.summary.avg_completion_rate) }}%</span>
            </div>
            <div v-if="reportData.summary?.total_teams" class="stat-item">
              <span class="stat-label">Total Teams</span>
              <span class="stat-value">{{ reportData.summary.total_teams }}</span>
            </div>
            <div v-if="reportData.summary?.total_departments" class="stat-item">
              <span class="stat-label">Total Departments</span>
              <span class="stat-value">{{ reportData.summary.total_departments }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Team Members Section (for team reports) -->
      <div v-if="reportData.detailed_data?.team_members?.length" class="report-section">
        <h2 class="section-title">Team Member Performance</h2>
        <a-table 
          :dataSource="reportData.detailed_data.team_members" 
          :columns="teamMemberColumns"
          :pagination="false"
          size="small"
          class="team-table"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.dataIndex === 'completion_rate'">
              <a-progress 
                :percent="Math.round((record.completed / record.total_tasks) * 100)" 
                :size="['small', 14]"
                :showInfo="true"
              />
            </template>
          </template>
        </a-table>
        
        <!-- Team Member Bar Chart -->
        <div class="bar-chart-section">
          <h3 class="chart-title">Task Status by Team Member</h3>
          <div class="bar-chart-container">
            <canvas ref="teamBarChartCanvas" width="500" height="300"></canvas>
          </div>
        </div>
      </div>

      <!-- Team/Department Comparison -->
      <div v-if="reportData.detailed_data?.team_comparison?.length || reportData.detailed_data?.department_comparison?.length" class="report-section">
        <h2 class="section-title">{{ getComparisonTitle() }}</h2>
        <a-table 
          :dataSource="getComparisonData()" 
          :columns="comparisonColumns"
          :pagination="false"
          size="small"
          class="comparison-table"
        />
      </div>

      <!-- Charts Section -->
      <div v-if="reportData.charts?.length > 1" class="report-section">
        <h2 class="section-title">Analytics</h2>
        <div class="charts-grid">
          <div v-for="(chart, index) in reportData.charts.slice(1)" :key="index" class="chart-container">
            <div class="chart-title">{{ chart.title }}</div>
            <div class="actual-chart-container">
              <canvas 
                :ref="el => { if (el) chartRefs[`chart_${index}`] = el }"
                width="400" 
                height="250"
                class="preview-chart-canvas"
                :data-chart-index="index"
              ></canvas>
            </div>
          </div>
        </div>
      </div>

      <!-- Sample Tasks Preview -->
      <div v-if="reportData.detailed_data?.tasks?.length" class="report-section">
        <h2 class="section-title">Sample Tasks (First 10)</h2>
        <a-table 
          :dataSource="reportData.detailed_data.tasks" 
          :columns="taskColumns"
          :pagination="false"
          size="small"
          class="task-table"
        />
      </div>

      <div class="report-footer">
        <small>Report generated at: {{ formatDate(reportData.generated_at) }}</small>
      </div>
    </div>

    <!-- Loading State -->
    <div v-else class="loading-container">
      <a-spin size="large" />
      <p>Loading report data...</p>
    </div>

    <!-- Footer Actions -->
    <div class="modal-actions">
      <a-button @click="handleClose" size="large">
        Cancel
      </a-button>
      <a-button
        type="primary"
        size="large"
        @click="handleExportPDF"
        :loading="isExporting"
        :icon="h(DownloadOutlined)"
      >
        Export to PDF
      </a-button>
    </div>
  </a-modal>
</template>

<script setup>
import { ref, computed, watch, h, nextTick } from 'vue'
import {
  FileTextOutlined,
  CloseOutlined,
  DownloadOutlined,
  PieChartOutlined
} from '@ant-design/icons-vue'

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true
  },
  reportData: {
    type: Object,
    default: null
  }
})

const emit = defineEmits(['close', 'export'])

const modalVisible = ref(false)
const isExporting = ref(false)
const pieChartCanvas = ref(null)
const teamBarChartCanvas = ref(null)
const chartRefs = ref({})

// Watch for prop changes
watch(() => props.isOpen, (newVal) => {
  modalVisible.value = newVal
}, { immediate: true })

// Watch for reportData changes to draw charts
watch(() => props.reportData, (newVal) => {
  if (newVal) {
    nextTick(() => {
      setTimeout(() => {
        drawPieChart()
        drawTeamBarChart()
        drawAnalyticsCharts()
      }, 100) // Small delay to ensure DOM is ready
    })
  }
}, { immediate: true })

const drawPieChart = () => {
  console.log('Drawing main pie chart...')
  if (!pieChartCanvas.value || !props.reportData?.charts?.length) {
    console.log('No canvas or no charts data')
    return
  }

  const canvas = pieChartCanvas.value
  const ctx = canvas.getContext('2d')
  
  // Find the first pie chart
  const pieChart = props.reportData.charts.find(chart => chart.type === 'pie')
  if (!pieChart || !pieChart.data) {
    console.log('No pie chart found in data')
    return
  }

  console.log('Pie chart data:', pieChart.data)

  // Clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height)

  // Prepare data
  const data = []
  const labels = []
  const colors = ['#22c55e', '#3b82f6', '#ef4444', '#a855f7', '#f59e0b', '#06b6d4']

  Object.entries(pieChart.data).forEach(([key, value]) => {
    if (typeof value === 'number' && value > 0) {
      data.push(value)
      labels.push(key)
    }
  })

  if (data.length === 0) {
    data.push(1)
    labels.push('No Data')
    colors[0] = '#e5e7eb'
  }

  console.log('Processed pie chart data:', { data, labels })

  // Calculate total
  const total = data.reduce((a, b) => a + b, 0)

  // Draw pie chart
  const centerX = canvas.width / 2
  const centerY = 150
  const radius = 120

  let startAngle = -Math.PI / 2

  data.forEach((value, index) => {
    const sliceAngle = (value / total) * 2 * Math.PI
    const color = colors[index % colors.length]

    // Draw slice
    ctx.beginPath()
    ctx.moveTo(centerX, centerY)
    ctx.arc(centerX, centerY, radius, startAngle, startAngle + sliceAngle)
    ctx.closePath()
    ctx.fillStyle = color
    ctx.fill()
    ctx.strokeStyle = '#ffffff'
    ctx.lineWidth = 3
    ctx.stroke()

    startAngle += sliceAngle
  })

  // Draw legend
  const legendStartY = 320
  let legendY = legendStartY
  const legendX = 30

  ctx.font = '14px Arial'
  ctx.textAlign = 'left'

  labels.forEach((label, index) => {
    const color = colors[index % colors.length]
    
    // Draw color box
    ctx.fillStyle = color
    ctx.fillRect(legendX, legendY - 12, 16, 16)

    // Draw text
    ctx.fillStyle = '#1f2937'
    ctx.fillText(`${label}: ${data[index]}`, legendX + 24, legendY)

    legendY += 28
  })
}

const drawTeamBarChart = () => {
  if (!teamBarChartCanvas.value || !props.reportData?.detailed_data?.team_members?.length) return

  const canvas = teamBarChartCanvas.value
  const ctx = canvas.getContext('2d')
  const teamMembers = props.reportData.detailed_data.team_members

  // Clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height)

  // Calculate dimensions
  const barWidth = 40
  const barSpacing = 60
  const leftMargin = 60
  const bottomMargin = 60
  const topMargin = 40

  const maxTotalTasks = Math.max(...teamMembers.map(member => member.total_tasks))
  const chartHeight = 200

  // Draw bars for each member
  teamMembers.forEach((member, i) => {
    const xPos = leftMargin + i * barSpacing
    
    // Calculate heights
    const totalHeight = (member.total_tasks / maxTotalTasks) * chartHeight
    const completedHeight = (member.completed / maxTotalTasks) * chartHeight
    
    // Draw total tasks bar (background)
    ctx.fillStyle = '#e5e7eb'
    ctx.fillRect(xPos, canvas.height - bottomMargin - totalHeight, barWidth, totalHeight)
    
    // Draw completed tasks bar (foreground)
    ctx.fillStyle = '#22c55e'
    ctx.fillRect(xPos, canvas.height - bottomMargin - completedHeight, barWidth, completedHeight)
    
    // Draw member name
    ctx.fillStyle = '#1f2937'
    ctx.font = '10px Arial'
    ctx.textAlign = 'center'
    ctx.fillText(
      member.name.length > 8 ? member.name.substring(0, 8) + '...' : member.name,
      xPos + barWidth/2,
      canvas.height - bottomMargin + 15
    )
    
    // Draw values above bar
    ctx.font = 'bold 9px Arial'
    ctx.fillText(
      `${member.completed}/${member.total_tasks}`,
      xPos + barWidth/2,
      canvas.height - bottomMargin - totalHeight - 5
    )
  })
  
  // Add title
  ctx.fillStyle = '#1f2937'
  ctx.font = 'bold 14px Arial'
  ctx.textAlign = 'center'
  ctx.fillText('Task Status by Team Member', canvas.width/2, 25)
  
  // Add legend
  const legendY = 50
  
  // Completed legend
  ctx.fillStyle = '#22c55e'
  ctx.fillRect(leftMargin, legendY, 15, 10)
  ctx.fillStyle = '#1f2937'
  ctx.font = '10px Arial'
  ctx.textAlign = 'left'
  ctx.fillText('Completed', leftMargin + 20, legendY + 8)
  
  // Total legend
  ctx.fillStyle = '#e5e7eb'
  ctx.fillRect(leftMargin + 100, legendY, 15, 10)
  ctx.fillStyle = '#1f2937'
  ctx.fillText('Total', leftMargin + 120, legendY + 8)
}

const drawAnalyticsCharts = () => {
  console.log('Drawing analytics charts...', props.reportData?.charts?.length)
  if (!props.reportData?.charts?.length) return

  // Use nextTick to ensure DOM is fully rendered
  nextTick(() => {
    // Draw each analytics chart (skip the first one which is the main pie chart)
    props.reportData.charts.slice(1).forEach((chart, index) => {
      setTimeout(() => {
        console.log(`Processing chart ${index}:`, chart.title, chart.type)
        
        const canvasRef = `chart_${index}`
        let canvas = chartRefs.value[canvasRef]
        
        // Fallback to DOM query if ref not available
        if (!canvas) {
          canvas = document.querySelector(`canvas[data-chart-index="${index}"]`)
          console.log('Canvas from DOM query:', !!canvas)
        }
        
        if (!canvas) {
          console.warn(`Canvas not found for chart ${index}`)
          return
        }

        const ctx = canvas.getContext('2d')
        ctx.clearRect(0, 0, canvas.width, canvas.height)

        console.log(`Drawing ${chart.type} chart:`, chart.title)
        
        if (chart.type === 'pie') {
          drawSmallPieChart(ctx, chart.data, chart.title, canvas.width, canvas.height)
        } else if (chart.type === 'bar') {
          drawSmallBarChart(ctx, chart.data, chart.title, canvas.width, canvas.height)
        }
      }, index * 50) // Stagger the drawing
    })
  })
}

const drawSmallPieChart = (ctx, data, title, width, height) => {
  console.log('Drawing enhanced pie chart:', title, data)
  if (!data || typeof data !== 'object') return

  const centerX = width / 2
  const centerY = (height / 2) + 15
  const radius = Math.min(width, height - 100) / 3

  const values = Object.values(data).filter(v => typeof v === 'number' && v > 0)
  const labels = Object.keys(data).filter(key => data[key] > 0)
  
  if (values.length === 0) {
    // Draw "No Data" message
    ctx.fillStyle = '#6b7280'
    ctx.font = '12px Arial'
    ctx.textAlign = 'center'
    ctx.fillText('No data available', centerX, centerY)
    return
  }

  const total = values.reduce((a, b) => a + b, 0)
  
  // Enhanced color palette
  const colorPalette = [
    '#3b82f6', '#22c55e', '#f59e0b', '#a855f7', 
    '#ef4444', '#06b6d4', '#8b5cf6', '#f97316'
  ]

  // Draw background circle for better contrast
  ctx.fillStyle = '#f8fafc'
  ctx.fillRect(0, 0, width, height)
  
  // Draw title with enhanced styling
  const gradient = ctx.createLinearGradient(0, 0, width, 0)
  gradient.addColorStop(0, '#1e40af')
  gradient.addColorStop(1, '#3b82f6')
  
  ctx.fillStyle = gradient
  ctx.font = 'bold 14px Arial'
  ctx.textAlign = 'center'
  ctx.fillText(title, centerX, 20)
  
  // Draw total value subtitle
  ctx.fillStyle = '#6b7280'
  ctx.font = '10px Arial'
  ctx.fillText(`Total: ${total}`, centerX, 35)

  let startAngle = -Math.PI / 2

  values.forEach((value, index) => {
    const sliceAngle = (value / total) * 2 * Math.PI
    const color = colorPalette[index % colorPalette.length]

    // Draw shadow
    ctx.beginPath()
    ctx.moveTo(centerX + 3, centerY + 3)
    ctx.arc(centerX + 3, centerY + 3, radius, startAngle, startAngle + sliceAngle)
    ctx.closePath()
    ctx.fillStyle = 'rgba(0, 0, 0, 0.1)'
    ctx.fill()

    // Draw main slice
    ctx.beginPath()
    ctx.moveTo(centerX, centerY)
    ctx.arc(centerX, centerY, radius, startAngle, startAngle + sliceAngle)
    ctx.closePath()
    ctx.fillStyle = color
    ctx.fill()
    
    // Add gradient effect
    const sliceGradient = ctx.createRadialGradient(
      centerX, centerY, 0, 
      centerX, centerY, radius
    )
    sliceGradient.addColorStop(0, color)
    sliceGradient.addColorStop(0.7, color)
    sliceGradient.addColorStop(1, color + '80') // Semi-transparent
    
    ctx.fillStyle = sliceGradient
    ctx.fill()
    
    // Add border
    ctx.strokeStyle = '#ffffff'
    ctx.lineWidth = 3
    ctx.stroke()

    // Draw percentage labels on slices (if slice is large enough)
    const percentage = ((value / total) * 100).toFixed(0)
    if (sliceAngle > 0.3) { // Only show if slice is > ~17 degrees
      const midAngle = startAngle + (sliceAngle / 2)
      const labelRadius = radius * 0.7
      const labelX = centerX + Math.cos(midAngle) * labelRadius
      const labelY = centerY + Math.sin(midAngle) * labelRadius
      
      ctx.fillStyle = '#ffffff'
      ctx.font = 'bold 10px Arial'
      ctx.textAlign = 'center'
      ctx.fillText(`${percentage}%`, labelX, labelY + 3)
    }

    startAngle += sliceAngle
  })

  // Draw enhanced legend with better layout
  const legendStartY = height - (labels.length * 16 + 10)
  const legendCols = Math.ceil(labels.length / 4) // Max 4 items per column
  const colWidth = width / legendCols

  labels.forEach((label, index) => {
    const col = Math.floor(index / 4)
    const row = index % 4
    const legendX = col * colWidth + 20
    const legendY = legendStartY + (row * 16)
    const color = colorPalette[index % colorPalette.length]
    
    // Draw colored square with border
    ctx.fillStyle = color
    ctx.fillRect(legendX, legendY - 8, 12, 12)
    ctx.strokeStyle = '#ffffff'
    ctx.lineWidth = 1
    ctx.strokeRect(legendX, legendY - 8, 12, 12)
    
    // Draw text with value and percentage
    ctx.fillStyle = '#1f2937'
    ctx.font = 'bold 10px Arial'
    ctx.textAlign = 'left'
    
    // Truncate long labels
    let labelText = label
    if (label.length > 10) {
      labelText = label.substring(0, 8) + '...'
    }
    
    const percentage = ((values[index] / total) * 100).toFixed(0)
    ctx.fillText(`${labelText}: ${values[index]} (${percentage}%)`, legendX + 16, legendY + 2)
  })
}

const drawSmallBarChart = (ctx, data, title, width, height) => {
  console.log('Drawing enhanced bar chart:', title, data)
  
  if (!data || typeof data !== 'object') {
    console.log('No data or invalid data type')
    return
  }

  // Handle both object and array data formats
  let keys, values
  
  if (Array.isArray(data)) {
    values = data.filter(v => typeof v === 'number' && v > 0)
    keys = values.map((_, i) => `Item ${i + 1}`)
  } else {
    keys = Object.keys(data).filter(key => {
      const value = data[key]
      return typeof value === 'number' && value > 0
    })
    values = keys.map(key => data[key])
  }
  
  console.log('Processed keys:', keys, 'values:', values)
  
  if (values.length === 0) {
    // Draw "No Data" message
    ctx.fillStyle = '#6b7280'
    ctx.font = '12px Arial'
    ctx.textAlign = 'center'
    ctx.fillText('No data available', width / 2, height / 2)
    return
  }

  const maxValue = Math.max(...values)
  const minBarHeight = 20
  const barSpacing = 28
  const leftMargin = 100
  const topMargin = 45
  const rightMargin = 50
  const bottomMargin = 20

  // Calculate dynamic dimensions
  const availableHeight = height - topMargin - bottomMargin
  const barHeight = Math.min(minBarHeight, (availableHeight / values.length) - 6)
  
  // Draw background
  ctx.fillStyle = '#f8fafc'
  ctx.fillRect(0, 0, width, height)
  
  // Draw title with enhanced styling
  const gradient = ctx.createLinearGradient(0, 0, width, 0)
  gradient.addColorStop(0, '#1e40af')
  gradient.addColorStop(1, '#3b82f6')
  
  ctx.fillStyle = gradient
  ctx.font = 'bold 14px Arial'
  ctx.textAlign = 'center'
  ctx.fillText(title, width / 2, 25)
  
  // Draw subtitle with max value
  ctx.fillStyle = '#6b7280'
  ctx.font = '10px Arial'
  ctx.fillText(`Max: ${maxValue}`, width / 2, 40)

  // Enhanced color palette with gradients
  const colorPairs = [
    ['#3b82f6', '#1d4ed8'], // Blue
    ['#22c55e', '#16a34a'], // Green  
    ['#f59e0b', '#d97706'], // Amber
    ['#a855f7', '#9333ea'], // Purple
    ['#ef4444', '#dc2626'], // Red
    ['#06b6d4', '#0891b2'], // Cyan
    ['#8b5cf6', '#7c3aed'], // Violet
    ['#f97316', '#ea580c']  // Orange
  ]

  keys.forEach((key, index) => {
    const value = values[index]
    const maxBarWidth = width - leftMargin - rightMargin
    const barWidth = Math.max((value / maxValue) * maxBarWidth, 8) // Minimum 8px width
    const y = topMargin + (index * barSpacing)
    const [color1, color2] = colorPairs[index % colorPairs.length]

    // Create gradient for bar
    const barGradient = ctx.createLinearGradient(leftMargin, y, leftMargin + barWidth, y)
    barGradient.addColorStop(0, color1)
    barGradient.addColorStop(1, color2)
    
    // Draw bar shadow
    ctx.fillStyle = 'rgba(0, 0, 0, 0.1)'
    ctx.fillRect(leftMargin + 2, y + 2, barWidth, barHeight)
    
    // Draw main bar
    ctx.fillStyle = barGradient
    ctx.fillRect(leftMargin, y, barWidth, barHeight)
    
    // Add glossy effect
    const glossGradient = ctx.createLinearGradient(leftMargin, y, leftMargin, y + barHeight/2)
    glossGradient.addColorStop(0, 'rgba(255, 255, 255, 0.3)')
    glossGradient.addColorStop(1, 'rgba(255, 255, 255, 0)')
    ctx.fillStyle = glossGradient
    ctx.fillRect(leftMargin, y, barWidth, barHeight/2)
    
    // Add border
    ctx.strokeStyle = color2
    ctx.lineWidth = 1
    ctx.strokeRect(leftMargin, y, barWidth, barHeight)

    // Draw label with better formatting
    ctx.fillStyle = '#374151'
    ctx.font = 'bold 11px Arial'
    ctx.textAlign = 'right'
    
    // Truncate long labels more intelligently
    let labelText = key
    if (key.length > 14) {
      const words = key.split(' ')
      if (words.length > 1 && words[0].length <= 14) {
        labelText = words[0] + '...'
      } else {
        labelText = key.substring(0, 11) + '...'
      }
    }
    ctx.fillText(labelText, leftMargin - 8, y + barHeight/2 + 4)

    // Draw value with background
    const valueText = value.toString()
    const valueMetrics = ctx.measureText(valueText)
    const valuePadding = 4
    
    ctx.fillStyle = 'rgba(255, 255, 255, 0.9)'
    ctx.fillRect(
      leftMargin + barWidth + 8, 
      y + 2, 
      valueMetrics.width + valuePadding * 2, 
      barHeight - 4
    )
    
    ctx.fillStyle = '#1f2937'
    ctx.font = 'bold 11px Arial'
    ctx.textAlign = 'left'
    ctx.fillText(valueText, leftMargin + barWidth + 8 + valuePadding, y + barHeight/2 + 4)
    
    // Add percentage if applicable
    const percentage = ((value / maxValue) * 100).toFixed(0)
    ctx.fillStyle = '#6b7280'
    ctx.font = '9px Arial'
    ctx.fillText(`(${percentage}%)`, leftMargin + barWidth + valueMetrics.width + 20, y + barHeight/2 + 4)
  })
  
  // Add grid lines for better readability
  ctx.strokeStyle = 'rgba(203, 213, 225, 0.5)'
  ctx.lineWidth = 1
  for (let i = 1; i <= 4; i++) {
    const gridX = leftMargin + ((width - leftMargin - rightMargin) * i / 4)
    ctx.beginPath()
    ctx.moveTo(gridX, topMargin)
    ctx.lineTo(gridX, height - bottomMargin)
    ctx.stroke()
  }
}

// Table columns
const teamMemberColumns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Total Tasks',
    dataIndex: 'total_tasks',
    key: 'total_tasks',
    align: 'center'
  },
  {
    title: 'Completed',
    dataIndex: 'completed',
    key: 'completed',
    align: 'center'
  },
  {
    title: 'In Progress',
    dataIndex: 'in_progress',
    key: 'in_progress',
    align: 'center'
  },
  {
    title: 'Overdue',
    dataIndex: 'overdue',
    key: 'overdue',
    align: 'center'
  },
  {
    title: 'Completion Rate',
    dataIndex: 'completion_rate',
    key: 'completion_rate',
    align: 'center'
  }
]

const comparisonColumns = [
  {
    title: 'Name',
    dataIndex: 'team_name',
    key: 'team_name',
    customRender: ({ record }) => record.team_name || record.department || record.scope_name
  },
  {
    title: 'Total Tasks',
    dataIndex: 'total_tasks',
    key: 'total_tasks',
    align: 'center'
  },
  {
    title: 'Completed',
    dataIndex: 'completed_tasks',
    key: 'completed_tasks',
    align: 'center'
  },
  {
    title: 'Completion Rate',
    key: 'completion_rate',
    align: 'center',
    customRender: ({ record }) => `${record.completion_rate?.toFixed(1) || 0}%`
  },
  {
    title: 'Overdue',
    dataIndex: 'overdue_tasks',
    key: 'overdue_tasks',
    align: 'center'
  }
]

const taskColumns = [
  {
    title: 'Task Title',
    dataIndex: 'title',
    key: 'title',
    width: '40%'
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    align: 'center'
  },
  {
    title: 'Priority',
    dataIndex: 'priority',
    key: 'priority',
    align: 'center'
  },
  {
    title: 'Due Date',
    key: 'due_date',
    align: 'center',
    customRender: ({ record }) => {
      const date = record.due_date
      if (!date) return 'N/A'
      try {
        return new Date(date).toLocaleDateString()
      } catch {
        return 'N/A'
      }
    }
  }
]

// Computed properties
const getReportTitle = () => {
  if (!props.reportData) return 'Report'
  
  const typeLabels = {
    'individual': 'Individual Report',
    'team': 'Team Report', 
    'department': 'Department Report',
    'organization': 'Organization Report'
  }
  
  return typeLabels[props.reportData.report_type] || 'Report'
}

const getTargetLabel = () => {
  if (!props.reportData) return ''
  
  const type = props.reportData.report_type
  if (type === 'individual') return 'Target User'
  if (type === 'team') return 'Team'
  if (type === 'department') return 'Department'
  if (type === 'organization') return 'Scope'
  return 'Target'
}

const getTargetInfo = () => {
  if (!props.reportData) return ''
  
  const summary = props.reportData.summary
  if (summary?.target_user) return summary.target_user
  if (summary?.team_name) return summary.team_name
  if (summary?.department) return summary.department
  if (summary?.scope_type) return `${summary.scope_type} analysis`
  return ''
}

const getFiltersInfo = () => {
  if (!props.reportData?.filters) return ''
  
  const filters = props.reportData.filters
  const parts = []
  
  if (filters.start_date && filters.end_date) {
    parts.push(`Date: ${filters.start_date} to ${filters.end_date}`)
  } else if (filters.start_date) {
    parts.push(`From: ${filters.start_date}`)
  } else if (filters.end_date) {
    parts.push(`Until: ${filters.end_date}`)
  }
  
  if (filters.status_filter && filters.status_filter.length > 0 && !filters.status_filter.includes('All')) {
    parts.push(`Status: ${filters.status_filter.join(', ')}`)
  }
  
  return parts.join(' | ') || 'No filters applied'
}

const getComparisonTitle = () => {
  if (!props.reportData) return 'Comparison'
  
  const type = props.reportData.report_type
  if (type === 'team') return 'Team Comparison'
  if (type === 'department') return 'Department Comparison'
  if (type === 'organization') return 'Organization Comparison'
  return 'Comparison'
}

const getComparisonData = () => {
  if (!props.reportData?.detailed_data) return []
  
  return props.reportData.detailed_data.team_comparison || 
         props.reportData.detailed_data.department_comparison || 
         props.reportData.detailed_data.scope_comparison || 
         []
}

const formatDate = (dateString) => {
  if (!dateString) return 'N/A'
  try {
    return new Date(dateString).toLocaleString()
  } catch {
    return 'N/A'
  }
}

const handleClose = () => {
  modalVisible.value = false
  emit('close')
}

const handleExportPDF = () => {
  emit('export')
}
</script>

<style scoped>
.report-preview-modal :deep(.ant-modal-body) {
  padding: 0;
  max-height: 80vh;
  overflow-y: auto;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 24px;
  border-bottom: 1px solid #f0f0f0;
  background: #fafafa;
}

.header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.icon-wrapper {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  align-items: center;
  justify-content: center;
}

.header-icon {
  font-size: 24px;
  color: white;
}

.header-text {
  flex: 1;
}

.modal-title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1f2937;
}

.modal-subtitle {
  margin: 4px 0 0 0;
  font-size: 14px;
  color: #6b7280;
}

.close-button {
  color: #6b7280;
}

.close-button:hover {
  color: #1f2937;
}

.report-content {
  padding: 24px;
}

.report-section {
  margin-bottom: 32px;
}

.section-title {
  font-size: 16px;
  font-weight: 600;
  color: #1e40af;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 2px solid #e5e7eb;
}

.overview-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}

.overview-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.overview-item.full-width {
  grid-column: 1 / -1;
}

.label {
  font-size: 12px;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.value {
  font-size: 14px;
  color: #1f2937;
}

.summary-container {
  display: flex;
  gap: 48px;
  align-items: flex-start;
}

.pie-chart-container {
  flex: 0 0 400px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: white;
  border-radius: 8px;
  padding: 16px;
}

.stats-cards {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.stat-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.stat-item.highlight {
  background: white;
  border: 2px solid #1890ff;
}

.stat-label {
  font-size: 13px;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.stat-value {
  font-size: 20px;
  font-weight: 700;
  color: #1f2937;
}

.stat-value.completed-color {
  color: #22c55e;
}

.charts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
}

.chart-container {
  border: 1px solid #e8e8e8;
  border-radius: 8px;
  padding: 16px;
  background: #fafafa;
}

.chart-title {
  font-weight: 600;
  margin-bottom: 12px;
  color: #333;
  text-align: center;
}

.chart-placeholder {
  text-align: center;
  padding: 20px;
  background: white;
  border-radius: 6px;
  border: 2px dashed #d9d9d9;
}

.chart-icon {
  font-size: 32px;
  color: #1890ff;
  margin-bottom: 12px;
  display: block;
}

.chart-data-preview {
  margin-top: 12px;
}

.pie-data, .bar-data {
  text-align: left;
}

.data-item {
  display: flex;
  justify-content: space-between;
  padding: 4px 0;
  border-bottom: 1px solid #f0f0f0;
}

.data-item:last-child {
  border-bottom: none;
}

.data-label {
  font-weight: 500;
  color: #666;
}

.data-value {
  color: #1890ff;
  font-weight: 600;
}

.member-data {
  padding: 6px 0;
  border-bottom: 1px solid #f0f0f0;
  font-size: 12px;
}

.member-data:last-child {
  border-bottom: none;
}

.team-table,
.comparison-table,
.task-table {
  margin-top: 8px;
}

.report-footer {
  margin-top: 24px;
  padding-top: 16px;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  color: #6b7280;
}

.loading-container {
  padding: 60px;
  text-align: center;
}

.loading-container p {
  margin-top: 16px;
  color: #6b7280;
}

.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 24px;
  border-top: 1px solid #f0f0f0;
  background: #fafafa;
}

.bar-chart-section {
  margin-top: 20px;
  padding: 16px;
  background: #f9f9f9;
  border-radius: 8px;
  border: 1px solid #e5e7eb;
}

.bar-chart-container {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 12px;
}

.chart-title {
  font-size: 16px;
  font-weight: 600;
  color: #1e40af;
  text-align: center;
  margin-bottom: 12px;
}

.actual-chart-container {
  display: flex;
  justify-content: center;
  align-items: center;
  background: white;
  border-radius: 8px;
  padding: 16px;
  border: 1px solid #e5e7eb;
}

.preview-chart-canvas {
  max-width: 100%;
  height: auto;
}

@media (max-width: 768px) {
  .summary-container {
    flex-direction: column;
  }

  .pie-chart-container {
    flex: 1;
    width: 100%;
  }

  .overview-grid {
    grid-template-columns: 1fr;
  }

  .charts-grid {
    grid-template-columns: 1fr;
  }
}
</style>