<template>
  <a-modal
    v-model:open="modalVisible"
    :title="null"
    :footer="null"
    :width="1200"
    :closable="false"
    :maskClosable="false"
    @cancel="handleClose"
    class="report-preview-modal"
  >
    <!-- Header -->
    <div class="modal-header">
      <div class="header-content">
        <div class="icon-wrapper">
          <FileTextOutlined class="header-icon" />
        </div>
        <div class="header-text">
          <h3 class="modal-title">{{ getReportTitle() }} Preview</h3>
          <p class="modal-subtitle">Review the report before exporting to PDF</p>
        </div>
      </div>
      <a-button
        type="text"
        @click="handleClose"
        class="close-button"
        :icon="h(CloseOutlined)"
      />
    </div>

    <!-- Report Content -->
    <div class="report-content" v-if="reportData">
      <!-- Report Overview -->
      <div class="report-section">
        <h2 class="section-title">Report Overview</h2>
        <div class="overview-grid">
          <div class="overview-item">
            <span class="label">Report Type:</span>
            <span class="value">{{ getReportTitle() }}</span>
          </div>
          <div class="overview-item">
            <span class="label">Generated By:</span>
            <span class="value">{{ reportData.generated_by }}</span>
          </div>
          <div class="overview-item">
            <span class="label">User Role:</span>
            <span class="value">{{ reportData.user_role }}</span>
          </div>
          <div class="overview-item">
            <span class="label">Generated At:</span>
            <span class="value">{{ formatDate(reportData.generated_at) }}</span>
          </div>
          <div v-if="getTargetInfo()" class="overview-item">
            <span class="label">{{ getTargetLabel() }}:</span>
            <span class="value">{{ getTargetInfo() }}</span>
          </div>
          <div v-if="getFiltersInfo()" class="overview-item full-width">
            <span class="label">Applied Filters:</span>
            <span class="value">{{ getFiltersInfo() }}</span>
          </div>
        </div>
      </div>

      <!-- Performance Summary -->
      <div class="report-section">
        <h2 class="section-title">Performance Summary</h2>
        <div class="summary-container">
          <!-- Pie Chart -->
          <div class="pie-chart-container" v-if="reportData.charts?.length > 0">
            <canvas ref="pieChartCanvas" width="400" height="450"></canvas>
          </div>

          <!-- Stats Cards -->
          <div class="stats-cards">
            <div class="stat-item">
              <span class="stat-label">Total Tasks</span>
              <span class="stat-value">{{ reportData.summary?.total_tasks || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.completed_tasks !== undefined" class="stat-item">
              <span class="stat-label">Completed</span>
              <span class="stat-value completed-color">{{ reportData.summary.completed_tasks || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.total_completed !== undefined" class="stat-item">
              <span class="stat-label">Total Completed</span>
              <span class="stat-value completed-color">{{ reportData.summary.total_completed || 0 }}</span>
            </div>
            <div v-if="reportData.summary?.total_members" class="stat-item">
              <span class="stat-label">Team Members</span>
              <span class="stat-value">{{ reportData.summary.total_members }}</span>
            </div>
            <div v-if="reportData.summary?.avg_completion_rate !== undefined" class="stat-item highlight">
              <span class="stat-label">Avg Completion Rate</span>
              <span class="stat-value">{{ Math.round(reportData.summary.avg_completion_rate) }}%</span>
            </div>
            <div v-if="reportData.summary?.total_teams" class="stat-item">
              <span class="stat-label">Total Teams</span>
              <span class="stat-value">{{ reportData.summary.total_teams }}</span>
            </div>
            <div v-if="reportData.summary?.total_departments" class="stat-item">
              <span class="stat-label">Total Departments</span>
              <span class="stat-value">{{ reportData.summary.total_departments }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Team Members Section (for team reports) -->
      <div v-if="reportData.detailed_data?.team_members?.length" class="report-section">
        <h2 class="section-title">Team Member Performance</h2>
        <a-table 
          :dataSource="reportData.detailed_data.team_members" 
          :columns="teamMemberColumns"
          :pagination="false"
          size="small"
          class="team-table"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.dataIndex === 'completion_rate'">
              <a-progress 
                :percent="Math.round((record.completed / record.total_tasks) * 100)" 
                :size="['small', 14]"
                :showInfo="true"
              />
            </template>
          </template>
        </a-table>
      </div>

      <!-- Team/Department Comparison -->
      <div v-if="reportData.detailed_data?.team_comparison?.length || reportData.detailed_data?.department_comparison?.length" class="report-section">
        <h2 class="section-title">{{ getComparisonTitle() }}</h2>
        <a-table 
          :dataSource="getComparisonData()" 
          :columns="comparisonColumns"
          :pagination="false"
          size="small"
          class="comparison-table"
        />
      </div>

      <!-- Charts Section -->
      <div v-if="reportData.charts?.length > 1" class="report-section">
        <h2 class="section-title">Additional Charts & Analytics</h2>
        <div class="charts-grid">
          <div v-for="(chart, index) in reportData.charts.slice(1)" :key="index" class="chart-container">
            <div class="chart-title">{{ chart.title }}</div>
            <div class="chart-placeholder">
              <PieChartOutlined v-if="chart.type === 'pie'" class="chart-icon" />
              <span v-else class="chart-icon">📊</span>
              <div class="chart-data-preview">
                <div v-if="chart.type === 'pie'" class="pie-data">
                  <div v-for="(value, key) in chart.data" :key="key" class="data-item">
                    <span class="data-label">{{ key }}:</span>
                    <span class="data-value">{{ value }}</span>
                  </div>
                </div>
                <div v-else-if="chart.type === 'bar'" class="bar-data">
                  <div v-if="chart.data.members">
                    <div v-for="(member, idx) in chart.data.members" :key="idx" class="member-data">
                      <strong>{{ member }}:</strong>
                      C:{{ chart.data.completed[idx] || 0 }}, 
                      P:{{ chart.data.pending[idx] || 0 }}, 
                      O:{{ chart.data.overdue[idx] || 0 }}
                    </div>
                  </div>
                  <div v-else>
                    <div v-for="(value, key) in chart.data" :key="key" class="data-item">
                      <span class="data-label">{{ key }}:</span>
                      <span class="data-value">{{ Array.isArray(value) ? value.join(', ') : value }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Sample Tasks Preview -->
      <div v-if="reportData.detailed_data?.tasks?.length" class="report-section">
        <h2 class="section-title">Sample Tasks (First 10)</h2>
        <a-table 
          :dataSource="reportData.detailed_data.tasks" 
          :columns="taskColumns"
          :pagination="false"
          size="small"
          class="task-table"
        />
      </div>

      <div class="report-footer">
        <small>Report generated at: {{ formatDate(reportData.generated_at) }}</small>
      </div>
    </div>

    <!-- Loading State -->
    <div v-else class="loading-container">
      <a-spin size="large" />
      <p>Loading report data...</p>
    </div>

    <!-- Footer Actions -->
    <div class="modal-actions">
      <a-button @click="handleClose" size="large">
        Cancel
      </a-button>
      <a-button
        type="primary"
        size="large"
        @click="handleExportPDF"
        :loading="isExporting"
        :icon="h(DownloadOutlined)"
      >
        Export to PDF
      </a-button>
    </div>
  </a-modal>
</template>

<script setup>
import { ref, computed, watch, h, nextTick } from 'vue'
import {
  FileTextOutlined,
  CloseOutlined,
  DownloadOutlined,
  PieChartOutlined
} from '@ant-design/icons-vue'

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true
  },
  reportData: {
    type: Object,
    default: null
  }
})

const emit = defineEmits(['close', 'export'])

const modalVisible = ref(false)
const isExporting = ref(false)
const pieChartCanvas = ref(null)

// Watch for prop changes
watch(() => props.isOpen, (newVal) => {
  modalVisible.value = newVal
}, { immediate: true })

// Watch for reportData changes to draw pie chart
watch(() => props.reportData, (newVal) => {
  if (newVal) {
    nextTick(() => {
      drawPieChart()
    })
  }
}, { immediate: true })

const drawPieChart = () => {
  if (!pieChartCanvas.value || !props.reportData?.charts?.length) return

  const canvas = pieChartCanvas.value
  const ctx = canvas.getContext('2d')
  
  // Find the first pie chart
  const pieChart = props.reportData.charts.find(chart => chart.type === 'pie')
  if (!pieChart || !pieChart.data) return

  // Clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height)

  // Prepare data
  const data = []
  const labels = []
  const colors = ['#22c55e', '#3b82f6', '#ef4444', '#a855f7', '#f59e0b', '#06b6d4']

  Object.entries(pieChart.data).forEach(([key, value]) => {
    if (value > 0) {
      data.push(value)
      labels.push(key)
    }
  })

  if (data.length === 0) {
    data.push(1)
    labels.push('No Data')
  }

  // Calculate total
  const total = data.reduce((a, b) => a + b, 0)

  // Draw pie chart
  const centerX = canvas.width / 2
  const centerY = 150
  const radius = 120

  let startAngle = -Math.PI / 2

  data.forEach((value, index) => {
    const sliceAngle = (value / total) * 2 * Math.PI
    const color = colors[index % colors.length]

    // Draw slice
    ctx.beginPath()
    ctx.moveTo(centerX, centerY)
    ctx.arc(centerX, centerY, radius, startAngle, startAngle + sliceAngle)
    ctx.closePath()
    ctx.fillStyle = color
    ctx.fill()
    ctx.strokeStyle = '#ffffff'
    ctx.lineWidth = 3
    ctx.stroke()

    startAngle += sliceAngle
  })

  // Draw legend
  const legendStartY = 320
  let legendY = legendStartY
  const legendX = 30

  ctx.font = '14px Arial'
  ctx.textAlign = 'left'

  labels.forEach((label, index) => {
    const color = colors[index % colors.length]
    
    // Draw color box
    ctx.fillStyle = color
    ctx.fillRect(legendX, legendY - 12, 16, 16)

    // Draw text
    ctx.fillStyle = '#1f2937'
    ctx.fillText(`${label}: ${data[index]}`, legendX + 24, legendY)

    legendY += 28
  })
}

// Table columns
const teamMemberColumns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Total Tasks',
    dataIndex: 'total_tasks',
    key: 'total_tasks',
    align: 'center'
  },
  {
    title: 'Completed',
    dataIndex: 'completed',
    key: 'completed',
    align: 'center'
  },
  {
    title: 'In Progress',
    dataIndex: 'in_progress',
    key: 'in_progress',
    align: 'center'
  },
  {
    title: 'Overdue',
    dataIndex: 'overdue',
    key: 'overdue',
    align: 'center'
  },
  {
    title: 'Completion Rate',
    dataIndex: 'completion_rate',
    key: 'completion_rate',
    align: 'center'
  }
]

const comparisonColumns = [
  {
    title: 'Name',
    dataIndex: 'team_name',
    key: 'team_name',
    customRender: ({ record }) => record.team_name || record.department || record.scope_name
  },
  {
    title: 'Total Tasks',
    dataIndex: 'total_tasks',
    key: 'total_tasks',
    align: 'center'
  },
  {
    title: 'Completed',
    dataIndex: 'completed_tasks',
    key: 'completed_tasks',
    align: 'center'
  },
  {
    title: 'Completion Rate',
    key: 'completion_rate',
    align: 'center',
    customRender: ({ record }) => `${record.completion_rate?.toFixed(1) || 0}%`
  },
  {
    title: 'Overdue',
    dataIndex: 'overdue_tasks',
    key: 'overdue_tasks',
    align: 'center'
  }
]

const taskColumns = [
  {
    title: 'Task Title',
    dataIndex: 'title',
    key: 'title',
    width: '40%'
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    align: 'center'
  },
  {
    title: 'Priority',
    dataIndex: 'priority',
    key: 'priority',
    align: 'center'
  },
  {
    title: 'Due Date',
    key: 'due_date',
    align: 'center',
    customRender: ({ record }) => {
      const date = record.due_date
      if (!date) return 'N/A'
      try {
        return new Date(date).toLocaleDateString()
      } catch {
        return 'N/A'
      }
    }
  }
]

// Computed properties
const getReportTitle = () => {
  if (!props.reportData) return 'Report'
  
  const typeLabels = {
    'individual': 'Individual Report',
    'team': 'Team Report', 
    'department': 'Department Report',
    'organization': 'Organization Report'
  }
  
  return typeLabels[props.reportData.report_type] || 'Report'
}

const getTargetLabel = () => {
  if (!props.reportData) return ''
  
  const type = props.reportData.report_type
  if (type === 'individual') return 'Target User'
  if (type === 'team') return 'Team'
  if (type === 'department') return 'Department'
  if (type === 'organization') return 'Scope'
  return 'Target'
}

const getTargetInfo = () => {
  if (!props.reportData) return ''
  
  const summary = props.reportData.summary
  if (summary?.target_user) return summary.target_user
  if (summary?.team_name) return summary.team_name
  if (summary?.department) return summary.department
  if (summary?.scope_type) return `${summary.scope_type} analysis`
  return ''
}

const getFiltersInfo = () => {
  if (!props.reportData?.filters) return ''
  
  const filters = props.reportData.filters
  const parts = []
  
  if (filters.start_date && filters.end_date) {
    parts.push(`Date: ${filters.start_date} to ${filters.end_date}`)
  } else if (filters.start_date) {
    parts.push(`From: ${filters.start_date}`)
  } else if (filters.end_date) {
    parts.push(`Until: ${filters.end_date}`)
  }
  
  if (filters.status_filter && filters.status_filter.length > 0 && !filters.status_filter.includes('All')) {
    parts.push(`Status: ${filters.status_filter.join(', ')}`)
  }
  
  return parts.join(' | ') || 'No filters applied'
}

const getComparisonTitle = () => {
  if (!props.reportData) return 'Comparison'
  
  const type = props.reportData.report_type
  if (type === 'team') return 'Team Comparison'
  if (type === 'department') return 'Department Comparison'
  if (type === 'organization') return 'Organization Comparison'
  return 'Comparison'
}

const getComparisonData = () => {
  if (!props.reportData?.detailed_data) return []
  
  return props.reportData.detailed_data.team_comparison || 
         props.reportData.detailed_data.department_comparison || 
         props.reportData.detailed_data.scope_comparison || 
         []
}

const formatDate = (dateString) => {
  if (!dateString) return 'N/A'
  try {
    return new Date(dateString).toLocaleString()
  } catch {
    return 'N/A'
  }
}

const handleClose = () => {
  modalVisible.value = false
  emit('close')
}

const handleExportPDF = () => {
  emit('export')
}
</script>

<style scoped>
.report-preview-modal :deep(.ant-modal-body) {
  padding: 0;
  max-height: 80vh;
  overflow-y: auto;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 24px;
  border-bottom: 1px solid #f0f0f0;
  background: #fafafa;
}

.header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.icon-wrapper {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  align-items: center;
  justify-content: center;
}

.header-icon {
  font-size: 24px;
  color: white;
}

.header-text {
  flex: 1;
}

.modal-title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1f2937;
}

.modal-subtitle {
  margin: 4px 0 0 0;
  font-size: 14px;
  color: #6b7280;
}

.close-button {
  color: #6b7280;
}

.close-button:hover {
  color: #1f2937;
}

.report-content {
  padding: 24px;
}

.report-section {
  margin-bottom: 32px;
}

.section-title {
  font-size: 16px;
  font-weight: 600;
  color: #1e40af;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 2px solid #e5e7eb;
}

.overview-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}

.overview-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.overview-item.full-width {
  grid-column: 1 / -1;
}

.label {
  font-size: 12px;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.value {
  font-size: 14px;
  color: #1f2937;
}

.summary-container {
  display: flex;
  gap: 48px;
  align-items: flex-start;
}

.pie-chart-container {
  flex: 0 0 400px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: white;
  border-radius: 8px;
  padding: 16px;
}

.stats-cards {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.stat-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.stat-item.highlight {
  background: white;
  border: 2px solid #1890ff;
}

.stat-label {
  font-size: 13px;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.stat-value {
  font-size: 20px;
  font-weight: 700;
  color: #1f2937;
}

.stat-value.completed-color {
  color: #22c55e;
}

.charts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
}

.chart-container {
  border: 1px solid #e8e8e8;
  border-radius: 8px;
  padding: 16px;
  background: #fafafa;
}

.chart-title {
  font-weight: 600;
  margin-bottom: 12px;
  color: #333;
  text-align: center;
}

.chart-placeholder {
  text-align: center;
  padding: 20px;
  background: white;
  border-radius: 6px;
  border: 2px dashed #d9d9d9;
}

.chart-icon {
  font-size: 32px;
  color: #1890ff;
  margin-bottom: 12px;
  display: block;
}

.chart-data-preview {
  margin-top: 12px;
}

.pie-data, .bar-data {
  text-align: left;
}

.data-item {
  display: flex;
  justify-content: space-between;
  padding: 4px 0;
  border-bottom: 1px solid #f0f0f0;
}

.data-item:last-child {
  border-bottom: none;
}

.data-label {
  font-weight: 500;
  color: #666;
}

.data-value {
  color: #1890ff;
  font-weight: 600;
}

.member-data {
  padding: 6px 0;
  border-bottom: 1px solid #f0f0f0;
  font-size: 12px;
}

.member-data:last-child {
  border-bottom: none;
}

.team-table,
.comparison-table,
.task-table {
  margin-top: 8px;
}

.report-footer {
  margin-top: 24px;
  padding-top: 16px;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  color: #6b7280;
}

.loading-container {
  padding: 60px;
  text-align: center;
}

.loading-container p {
  margin-top: 16px;
  color: #6b7280;
}

.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 24px;
  border-top: 1px solid #f0f0f0;
  background: #fafafa;
}

@media (max-width: 768px) {
  .summary-container {
    flex-direction: column;
  }

  .pie-chart-container {
    flex: 1;
    width: 100%;
  }

  .overview-grid {
    grid-template-columns: 1fr;
  }

  .charts-grid {
    grid-template-columns: 1fr;
  }
}
</style>